on: push
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      #      - name: Set environment secrets
      #        env:
      #          FIREBASE_APP_DISTRIBUTION_KEY_STRING: ${{secrets.FIREBASE_APP_DISTRIBUTION_KEY_BASE_64}}
      #          PLAY_STORE_KEY_STRING: ${{secrets.PLAY_STORE_KEY_BASE_64}}
      #          KEYSTORE_STRING: ${{secrets.KEYSTORE_BASE_64}}
      #          KEYSTORE_ALIAS: ${{secrets.KEYSTORE_ALIAS}}
      #          KEYSTORE_PASSWORD: ${{secrets.KEYSTORE_PASSWORD}}
      #        run: |
      #          echo "FIREBASE_APP_DISTRIBUTION_KEY_STRING=$FIREBASE_APP_DISTRIBUTION_KEY_STRING" >> $GITHUB_ENV
      #          echo "PLAY_STORE_KEY_STRING=$PLAY_STORE_KEY_STRING" >> $GITHUB_ENV
      #          echo "KEYSTORE_STRING=$KEYSTORE_STRING" >> $GITHUB_ENV
      #          echo "KEYSTORE_ALIAS=$KEYSTORE_ALIAS" >> $GITHUB_ENV
      #          echo "KEYSTORE_PASSWORD=$KEYSTORE_PASSWORD" >> $GITHUB_ENV

      - name: Setup JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: "zulu"
          java-version: 11

      - name: Setup ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7

      - name: Setup android SDK
        uses: android-actions/setup-android@v2

      - name: Install dependencies to support ruby project
        working-directory: android
        run: |
          bundle config --global set deploy_platform_default x86_64-linux
          bundle install

      - name: Decode and create Firebase app distribution key file
        working-directory: android
        env:
          FIREBASE_APP_DISTRIBUTION_KEY_STRING: ${{secrets.FIREBASE_APP_DISTRIBUTION_KEY_BASE_64}}
        run: |
          FILE_PATH=certificates
          mkdir "${FILE_PATH}"
          pwd | rev
          echo $FIREBASE_APP_DISTRIBUTION_KEY_STRING | base64 -di > "${FILE_PATH}"/firebase-app-distribution-key.json

      - name: Decode and create Playstore app distribution key file
        working-directory: android
        env:
          PLAY_STORE_KEY_STRING: ${{secrets.FIREBASE_APP_DISTRIBUTION_KEY_BASE_64}}
        run: |
          FILE_PATH=certificates
          echo $PLAY_STORE_KEY_STRING | base64 -di > "${FILE_PATH}"/playstore-app-distribution-key.json

      - name: Decode and create keystore file
        working-directory: android
        env:
          KEYSTORE_STRING: ${{secrets.KEYSTORE_BASE_64}}
        run: |
          FILE_PATH=certificates
          echo $KEYSTORE_STRING | base64 -di > "${FILE_PATH}"/keystore.jks

      - name: Decode and create Google service key file
        working-directory: android
        env:
          GOOGLE_SERVICE_KEY_BASE_64: ${{secrets.GOOGLE_SERVICE_KEY_BASE_64}}
        run: |
          FILE_PATH=app
          echo $GOOGLE_SERVICE_KEY_BASE_64 | base64 -di > "${FILE_PATH}"/google-services.json

      - name: Install dart
        uses: dart-lang/setup-dart@v1

      - name: Install flutter
        run: |
          sudo snap install flutter --classic

      - name: Pub get install
        run: |
          - flutter pub get

      - name: Build and distribute app
        working-directory: android
        env:
          KEYSTORE_ALIAS: ${{ secrets.KEYSTORE_ALIAS }}
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
        run: |
          export LC_ALL=en_US.UTF-8
          export LANG=en_US.UTF-8
          gradle wrapper
          bundle exec fastlane build